# Generated by Django 5.2.6 on 2025-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Direct", "direct"), ("Group", "group")],
                max_length=50,
                null=True,
            ),
        ),
    ]
