# Generated by Django 5.2.6 on 2025-09-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0003_messages"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Messages",
            new_name="Message",
        ),
    ]
