# Generated by Django 5.2.6 on 2025-09-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatting", "0004_rename_messages_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="participant",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("admin", "Admin"), ("member", "Member")],
                max_length=10,
            ),
        ),
    ]
