# Generated by Django 5.2.6 on 2025-09-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="sender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
